name: Build OpenWRT Images
on: [push]

jobs:
    build:
        name: Prepare and build OpenWRT images
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install build dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y python3.13

            - name: Build target images
              run: |
                bash build_gli_yellow.sh

            - name: TAR output
              run: tar -cvf images.tar images

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: images
                path: images.tar

    release:
          name: Make a release
          runs-on: ubuntu-latest
          needs: build

          steps:
            - name: Download the image artifacts
              uses: actions/download-artifact@v4
              with:
                name: images

            - name: Extract the image artifacts
              run: tar xf images.tar

            - name: Get the current date
              run: echo "NOW=$(date +%F)" >> $GITHUB_ENV

            - name: Create a release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GIT_TOKEN }}"
                prerelease: false
                title: "OpenWRT PrivateRouter"
                automatic_release_tag: "OpenWRT-PrivateRouter"
                files: images/*
